llm:
  api_type: 'spark'
  app_id: '717d2dd4'
  api_key: '60ff7083c95574a034dbfce1b8b41ec2'
  api_secret: 'MWIxMTJmOWI3NGE1OGJhYTE5YWNiYjll'
  domain: 'generalv2'
  base_url: 'wss://spark-api.xf-yun.com/v3.5/chat'